-- ═══════════════════════════════════════════════════════════
--  DAILY COMMAND CENTER — Database Schema
--  Run this in Supabase SQL Editor (one time, in order)
-- ═══════════════════════════════════════════════════════════

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ─────────────────────────────────────────────────────────────
--  1. PROFILES
--  One row per user. Created automatically on signup via trigger.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text not null,
  full_name     text,
  tier          text not null default 'standard'
                  check (tier in ('standard', 'premium')),
  -- Premium customization fields
  org_name      text,
  org_mission   text,
  org_logo_url  text,
  primary_color text default '#1B4332',
  accent_color  text default '#C9A84C',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Auto-create profile on new user signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─────────────────────────────────────────────────────────────
--  2. ACCESS CODES
--  Generated by admin (you), redeemed once by buyer.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.access_codes (
  id            uuid primary key default gen_random_uuid(),
  code          text not null unique,
  tier          text not null default 'standard'
                  check (tier in ('standard', 'premium')),
  redeemed      boolean not null default false,
  redeemed_by   uuid references public.profiles(id) on delete set null,
  redeemed_at   timestamptz,
  etsy_order_id text,                -- optional, for your records
  created_at    timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
--  3. JOURNAL ENTRIES
--  One row per user per day.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.journal_entries (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  entry_date  date not null,
  data        jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, entry_date)       -- one entry per user per day, enforced at DB level
);

-- Index for fast per-user date lookups
create index if not exists idx_journal_user_date
  on public.journal_entries (user_id, entry_date desc);

-- Auto-update updated_at timestamp
create or replace function public.set_updated_at()
returns trigger language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger journal_updated_at
  before update on public.journal_entries
  for each row execute procedure public.set_updated_at();

create trigger profile_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();

-- ─────────────────────────────────────────────────────────────
--  4. ROW LEVEL SECURITY (RLS)
--  Every user can only see and edit their own data.
--  This is enforced at the database level — not just in code.
-- ─────────────────────────────────────────────────────────────
alter table public.profiles        enable row level security;
alter table public.journal_entries enable row level security;
alter table public.access_codes    enable row level security;

-- Profiles: users see and edit only their own row
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id);

-- Journal: users see and edit only their own entries
create policy "journal_select_own" on public.journal_entries
  for select using (auth.uid() = user_id);

create policy "journal_insert_own" on public.journal_entries
  for insert with check (auth.uid() = user_id);

create policy "journal_update_own" on public.journal_entries
  for update using (auth.uid() = user_id);

create policy "journal_delete_own" on public.journal_entries
  for delete using (auth.uid() = user_id);

-- Access codes: users cannot read the codes table directly.
-- Code redemption is handled server-side with the service role key.
-- No public policy = no public access. Full stop.

-- ─────────────────────────────────────────────────────────────
--  5. STORAGE BUCKET (for premium logo uploads)
-- ─────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'logos',
  'logos',
  false,                                -- private bucket
  2097152,                              -- 2 MB max per file
  array['image/png','image/jpeg','image/webp','image/svg+xml']
)
on conflict (id) do nothing;

-- Users can upload only to their own folder: logos/{user_id}/
create policy "logos_insert_own" on storage.objects
  for insert with check (
    bucket_id = 'logos' and
    auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "logos_select_own" on storage.objects
  for select using (
    bucket_id = 'logos' and
    auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "logos_delete_own" on storage.objects
  for delete using (
    bucket_id = 'logos' and
    auth.uid()::text = (storage.foldername(name))[1]
  );
